name: Push and upload

on:
  workflow_dispatch:

jobs:
  uploads:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Set up JDK-11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Build Jar file
        run: mvn clean install

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/register-employee:latest

      - name: Upload Jar file
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: target/*.jar